[versions]
# libraries
junit = "4.13.2"

jqa = "2.8.0"

maven-bom = "3.9.9"

graphstream = "2.0"


# plugins
changelog = "2.2.1"
intelliJPlatform = "2.11.0"
kotlin = "2.3.0"
ktlint = "12.1.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }

jqa-core-report = { group = "com.buschmais.jqassistant.core", name = "report", version.ref = "jqa" }
jqa-core-schemata = { group = "com.buschmais.jqassistant.core", name = "schemata", version.ref = "jqa" }
jqa-core-configuration = { group = "com.buschmais.jqassistant.core", name = "configuration", version.ref = "jqa" }
jqa-core-runtime = { group = "com.buschmais.jqassistant.core", name = "runtime", version.ref = "jqa" }
jqa-cli-application = { group = "com.buschmais.jqassistant.cli", name = "application", version.ref = "jqa" }
jqa-maven-plugin = { group = "com.buschmais.jqassistant", name = "jqassistant-maven-plugin", version.ref = "jqa" }
jqa-plugin-common = { group = "com.buschmais.jqassistant.plugin", name = "common", version.ref = "jqa" }

gs-core = { group = "org.graphstream", name = "gs-core", version.ref = "graphstream" }
gs-ui-swing = { group = "org.graphstream", name = "gs-ui-swing", version.ref = "graphstream" }

maven-bom = { module = "org.apache.maven:maven-bom", version.ref = "maven-bom" }
maven-core = { group = "org.apache.maven", name = "maven-core", version.ref = "maven-bom" }
maven-compat = { group = "org.apache.maven", name = "maven-compat", version.ref = "maven-bom" }
maven-model = { group = "org.apache.maven", name = "maven-model", version.ref = "maven-bom" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
